function normalForFace(vertices, face) {
  const a = vertices[face[0]];
  const b = vertices[face[1]];
  const c = vertices[face[2]];
  const ux = b[0] - a[0];
  const uy = b[1] - a[1];
  const uz = b[2] - a[2];
  const vx = c[0] - a[0];
  const vy = c[1] - a[1];
  const vz = c[2] - a[2];
  const nx = uy * vz - uz * vy;
  const ny = uz * vx - ux * vz;
  const nz = ux * vy - uy * vx;
  const length = Math.hypot(nx, ny, nz) || 1;
  return [nx / length, ny / length, nz / length];
}

export function exportPly(mesh) {
  const lines = [
    'ply',
    'format ascii 1.0',
    `comment generated by Kai 3D Capture`,
    `element vertex ${mesh.vertices.length}`,
    'property float x',
    'property float y',
    'property float z',
    'property uchar red',
    'property uchar green',
    'property uchar blue',
    `element face ${mesh.faces.length}`,
    'property list uchar int vertex_indices',
    'end_header'
  ];
  for (let index = 0; index < mesh.vertices.length; index += 1) {
    const vertex = mesh.vertices[index];
    const color = mesh.colors[index] || [0.8, 0.8, 0.8];
    lines.push([
      vertex[0].toFixed(4),
      vertex[1].toFixed(4),
      vertex[2].toFixed(4),
      Math.round(color[0] * 255),
      Math.round(color[1] * 255),
      Math.round(color[2] * 255)
    ].join(' '));
  }
  for (const face of mesh.faces) {
    lines.push(`3 ${face[0]} ${face[1]} ${face[2]}`);
  }
  return `${lines.join('\n')}\n`;
}

export function exportObj(mesh) {
  const lines = [
    '# Kai 3D Capture OBJ',
    `# units: ${mesh.units}`,
    `o ${mesh.name}`
  ];
  for (let index = 0; index < mesh.vertices.length; index += 1) {
    const vertex = mesh.vertices[index];
    const color = mesh.colors[index] || [0.8, 0.8, 0.8];
    lines.push(`v ${vertex[0].toFixed(4)} ${vertex[1].toFixed(4)} ${vertex[2].toFixed(4)} ${color[0].toFixed(4)} ${color[1].toFixed(4)} ${color[2].toFixed(4)}`);
  }
  for (const face of mesh.faces) {
    lines.push(`f ${face[0] + 1} ${face[1] + 1} ${face[2] + 1}`);
  }
  return `${lines.join('\n')}\n`;
}

export function exportStl(mesh) {
  const lines = [`solid ${mesh.name}`];
  for (const face of mesh.faces) {
    const normal = normalForFace(mesh.vertices, face);
    lines.push(`  facet normal ${normal[0].toExponential(6)} ${normal[1].toExponential(6)} ${normal[2].toExponential(6)}`);
    lines.push('    outer loop');
    for (const index of face) {
      const vertex = mesh.vertices[index];
      lines.push(`      vertex ${vertex[0].toFixed(4)} ${vertex[1].toFixed(4)} ${vertex[2].toFixed(4)}`);
    }
    lines.push('    endloop');
    lines.push('  endfacet');
  }
  lines.push(`endsolid ${mesh.name}`);
  return `${lines.join('\n')}\n`;
}

export function exportBundle(job, mesh, manifest) {
  return {
    ply: exportPly(mesh),
    obj: exportObj(mesh),
    stl: exportStl(mesh),
    manifest: `${JSON.stringify(manifest, null, 2)}\n`,
    mesh: `${JSON.stringify({ job, mesh }, null, 2)}\n`
  };
}

